version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Baku
    - AIRFLOW__WEBSERVER__SECRET_KEY=bank_pipeline_secret_key_2026
  
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/spark/data
    - ./jobs:/opt/spark/jobs
    - ./jars:/opt/spark/work-dir/jars

  depends_on:
    - postgres

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_ROLE=Admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - postgres

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init
      - postgres

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spark-master:
    image: apache/spark:3.5.2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/spark/data
      - ./jobs:/opt/spark/jobs
      - ./jars:/opt/spark/work-dir/jars


  spark-worker:
    image: apache/spark:3.5.2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark/data
      - ./jobs:/opt/spark/jobs
      - ./jars:/opt/spark/work-dir/jars


  jupyter:
    image: quay.io/jupyter/pyspark-notebook:x86_64-spark-3.5.2
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=admin
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/home/jovyan/jars
      - ./data:/home/jovyan/data
  frontend:
    image: python:3.10-slim
    command: bash -c "pip install streamlit pandas s3fs pyarrow && streamlit run /app/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - minio
volumes:
  minio_data:


